### ISSUE TITLE
Add more verbosity to the log

### ISSUE THREAD

**Issue by wschoenell** [pablogsal/fits_reduce#3]
Although I love the progress bar, I hate that it is the only one progress indicator... I'd put on the log a note when changing one file to another and even when doing master, dark, overscan and cosmic ray removal. This would be nice to have an idea of how much time we spend on each task for each image. Now the log on this part of the process is just this:

```
INFO - 2015-10-19 22:09:38,934 - reducer.reducer_tools - Starting the calibration of the science images
INFO - 2015-10-19 22:09:38,955 - reducer.reducer_tools - Now calibrating filter: R
INFO - 2015-10-19 22:09:38,956 - reducer.reducer_tools - Now calibrating exposure: 30
          (add more info here, pliz!)
INFO - 2015-10-19 23:05:59,223 - reducer - 1 nights of 1 correctly callibrated! :)
```

**Comment by pablogsal** [comment]
Do you think we should remove the progress bar?

I'm not sure that we can have both things at the same time.

**Comment by wschoenell** [comment]
We could either have `-vv` option which would disable the progress bar and be more verbose or separate the logs. The second option would be one log with less information to be shown on stdout with the progress bar and another log with more verbosity to be saved on the file. What you think?

**Comment by pablogsal** [comment]
I think that the stdout is not for analyse things. But it would be easier to implement the `-vv` option. What do you prefer?

**Comment by wschoenell** [comment]
`-vv` seems easy and elegant :-)
