### ISSUE TITLE
Different calibration files directory path

### ISSUE THREAD

**Issue by wschoenell** [pablogsal/fits_reduce#4]
Add an option on the command line to choose a different calibration files path to store the data. Also, move the log file to inside the calibration directory wherever it is.

**Comment by wschoenell** [comment]
I tested and found two problems:
1) When using `--savedir savedir/` it does not saves on `savedir/` but instead saves on a directory named `savedir/calibrated/`.

2) The log is still being saved on the input data directory.

**Comment by pablogsal** [comment]
Sorry, that was a mistake. Trying to correct that again.

**Comment by pablogsal** [comment]
Problems with the log file dir founded. I'm correcting those.
