### ISSUE TITLE
Add config option for the images units

### ISSUE THREAD

**Issue by wschoenell** [pablogsal/fits_reduce#5]
Images units are hardcoded (see link below for an example). Define a straightforward way to define images units. I think that the best way is to specify on the configuration file.

https://github.com/pablogsal/fits_reduce/blob/7d173101116cf69a525513383116c87e205a22bf/reducer_tools.py#L394

**Comment by pablogsal** [comment]
I agree on the configuration file units. But remember that ccdproc needs astropy.units objects.

**Comment by wschoenell** [comment]
CCDData can have units of `str` type.

https://github.com/astropy/ccdproc/blob/aee0777a308b0057a702f72dc39dc651e2408c3f/ccdproc/ccddata.py#L64-L65
