### ISSUE TITLE
Continuous integration needed

### ISSUE THREAD

**Issue by pablogsal** [pablogsal/fits_reduce#8]
We need to start thinking about implementing unit testing and CI for this project. The following tasks are needed:
- [ ] Describe useful unit tests to implement.
- [ ] Assign the different tasks. 
- [ ] Develop the unit testing.
- [x] Start Continuous integration.

**Comment by pablogsal** [comment]
Travis-CI fails the last PR with the code:

```
The command "git clone --depth=50 --branch=master https://github.com/pablogsal/fits_reduce.git pablogsal/fits_reduce" failed and exited with 128 during .
```

Something wrong with Travis-CI config?

**Comment by wschoenell** [comment]
Can you try restart the build from the travis-ci interface? This error is
probably because the github was unreachable from some reason from the
travis-ci side.

**Comment by pablogsal** [comment]
Yup, test passing. I have added a status image in the readme.

**Comment by wschoenell** [comment]
We could start the reducer unittesting by making the script file something like:

```python
from fits_reduce.main.reducer_tools import main

if __name__ == '__main__':
    main(sys.argv)
```

This follows the strategy shown in http://stackoverflow.com/questions/16916880/how-to-test-command-line-scripts-with-nose

**Comment by pablogsal** [comment]
If i understand it well, you mean in the reducer.py script? Or in the reducer_tools.py library?

**Comment by pablogsal** [comment]
Yeah, good idea. But we need to plan the unit tests first, no?

**Comment by wschoenell** [comment]
You don't have to plan too much. You just run a code coverage test on the code and make tests to all the methods that are not tested. You can do simple tests to begin with and then with the evolution of the code, add more tests for specific scenarios.

Since the scripts are outside the package, they are not mapped by the coverage test. This is why we should move it to what I mentioned before.

An example of such coverage test can be:
```
(fits_reduce)Williams-MacBook-Pro:fits_reduce william$ nosetests --with-coverage --cover-package=fits_reduce --cover-inclusive
..
Name                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------
fits_reduce                          1      0   100%   
fits_reduce.main                     1      0   100%   
fits_reduce.main.reducer_tools     251    218    13%   35-52, 62-67, 80-99, 113-124, 168-263, 270-295, 311-314, 350-655
fits_reduce.util                     1      0   100%   
fits_reduce.util.config             44      7    84%   53, 76, 78-79, 89, 97-99
fits_reduce.util.slices              5      0   100%   
--------------------------------------------------------------
TOTAL                              303    225    26%   
----------------------------------------------------------------------
Ran 2 tests in 3.310s

OK
```

If you want something fancier to have badges and so on like on travis-ci, you can take a look on on coveralls: https://coveralls.io/

**Comment by pablogsal** [comment]
Travis-CI gave an error regarding --with-coverage:

```
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
```

That's a problem?

**Comment by wschoenell** [comment]
You fixed it already :-p

**Comment by pablogsal** [comment]
I have added coveralls support to Travis-CI and the problem I mention is gone (obviously). We have now nice badges!
